# site settings
title: Rafaascensao
subtitle: Personal Website
email: rafascen@gmail.com
description: My personal website.
baseurl: "/personal-website" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Lisbon
state: 
zip_code: 
country: Portugal
phone: (+351) 918072404

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rafaascensao
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/barriganegra/
linkedin_url: https://www.linkedin.com/in/pedroascensao/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
